/*
 * Copyright 2026 默檐
 * SPDX-License-Identifier: Apache-2.0
 *
 * 本项目（LiquidGlass-Cpp）是基于 Kyant 项目的 C++ 独立移植与二次开发。
 * 项目开源地址：[https://github.com/SilentEaves/LiquidGlass-Cpp.git]
 *
 * ==================== 声明 ====================
 * 本项目由 默檐 于 2026 年独立完成 C++ 移植与二次修改。
 * 具体修改包括：将原项目（Kotlin）逻辑重写为 C++。
 * 本项目同样遵守并应用 Apache License, Version 2.0 协议。
 * ====================================================
 *
 * ------------------------------------------------------------------------
 * 第三方开源项目声明：
 * 本文件的核心代码逻辑移植自 AndroidLiquidGlass 项目，来源 Kyant 的液态玻璃项目。
 *
 * 原项目版权：Copyright 2025 Kyant
 * 原项目地址：https://github.com/Kyant0/AndroidLiquidGlass
 * 原项目许可证：Apache License, Version 2.0
 * 原项目许可证链接：http://www.apache.org/licenses/LICENSE-2.0
 * ------------------------------------------------------------------------
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "GlassContext.h"

namespace lgx {
namespace detail {
namespace {

const char* const kQuadVertexSource =
    "#version 300 es\n"
    "precision highp float;\n"
    "uniform vec4 uFrameRect;\n"
    "uniform vec2 uViewSpan;\n"
    "out vec2 vLocal;\n"
    "void main() {\n"
    "    float pickX = (gl_VertexID == 1 || gl_VertexID == 2 || gl_VertexID == 4) ? 1.0 : 0.0;\n"
    "    float pickY = (gl_VertexID == 2 || gl_VertexID == 4 || gl_VertexID == 5) ? 1.0 : 0.0;\n"
    "    vec2 local = vec2(pickX, pickY) * uFrameRect.zw;\n"
    "    vec2 device = uFrameRect.xy + local;\n"
    "    vec2 clip = vec2(device.x * 2.0 / uViewSpan.x - 1.0,\n"
    "                     1.0 - device.y * 2.0 / uViewSpan.y);\n"
    "    gl_Position = vec4(clip, 0.0, 1.0);\n"
    "    vLocal = local;\n"
    "}\n";

const char* const kGatherFragmentSource =
    "#version 300 es\n"
    "precision highp float;\n"
    "in vec2 vLocal;\n"
    "out vec4 fragOut;\n"
    "uniform sampler2D uGatherSource;\n"
    "uniform vec2 uSourceTexel;\n"
    "uniform vec2 uRegionSpan;\n"
    "uniform vec2 uAxisDir;\n"
    "uniform float uAxisStep;\n"
    "uniform float uTapMass[12];\n"
    "uniform vec2 uFboPitch;\n"
    "uniform float uBoxHalf;\n"
    "vec4 readRegion(vec2 regionPos) {\n"
    "    vec2 uv = vec2(regionPos.x / uSourceTexel.x,\n"
    "                   (uRegionSpan.y - regionPos.y) / uSourceTexel.y);\n"
    "    vec2 limit = max((uRegionSpan - vec2(0.5)) / uSourceTexel, vec2(0.0));\n"
    "    return texture(uGatherSource, clamp(uv, vec2(0.0), limit));\n"
    "}\n"
    "vec4 readTap(vec2 regionPos) {\n"
    "    if (uBoxHalf < 0.5) return readRegion(regionPos);\n"
    "    vec2 arm = vec2(uBoxHalf);\n"
    "    return (readRegion(regionPos + vec2(arm.x, arm.y))\n"
    "          + readRegion(regionPos + vec2(-arm.x, arm.y))\n"
    "          + readRegion(regionPos + vec2(arm.x, -arm.y))\n"
    "          + readRegion(regionPos + vec2(-arm.x, -arm.y))) * 0.25;\n"
    "}\n"
    "void main() {\n"
    "    vec2 anchor = vec2(gl_FragCoord.x * uFboPitch.x,\n"
    "                       uRegionSpan.y - gl_FragCoord.y * uFboPitch.y);\n"
    "    vec4 sum = readTap(anchor);\n"
    "    float norm = 1.0;\n"
    "    for (int k = 0; k < 12; ++k) {\n"
    "        float mass = uTapMass[k];\n"
    "        vec2 stride = uAxisDir * (uAxisStep * float(k + 1));\n"
    "        sum += (readTap(anchor + stride) + readTap(anchor - stride)) * mass;\n"
    "        norm += 2.0 * mass;\n"
    "    }\n"
    "    fragOut = sum / norm;\n"
    "}\n"
;

const char* const kPanelFragmentSource =
    "#version 300 es\n"
    "precision highp float;\n"
    "in vec2 vLocal;\n"
    "out vec4 fragOut;\n"
    "uniform sampler2D uScene;\n"
    "uniform sampler2D uGathered;\n"
    "uniform float uGatheredOn;\n"
    "uniform vec2 uGatherPitch;\n"
    "uniform float uGatherRows;\n"
    "uniform vec2 uGatherTexel;\n"
    "uniform vec2 uGatherLimit;\n"
    "uniform vec2 uPanelSpan;\n"
    "uniform vec2 uSampleShift;\n"
    "uniform vec2 uSampleSpan;\n"
    "uniform vec2 uSampleTexel;\n"
    "uniform vec4 uCornerRadii;\n"
    "uniform vec4 uDropRect;\n"
    "uniform float uDropRound;\n"
    "uniform vec4 uFeedRect;\n"
    "uniform float uFeedRound;\n"
    "uniform float uFeedMerge;\n"
    "uniform vec4 uStrandRect;\n"
    "uniform float uStrandRound;\n"
    "uniform float uStrandMerge;\n"
    "uniform float uLensHeight;\n"
    "uniform float uLensAmount;\n"
    "uniform float uLensDepth;\n"
    "uniform float uDarkGuard;\n"
    "uniform float uSpectral;\n"
"uniform float uPrismDist[3];\n"
"uniform float uPrismEvenRed[3];\n"
"uniform float uPrismOddRed[3];\n"
"uniform float uPrismEvenGreen[3];\n"
"uniform float uPrismOddGreen[3];\n"
"uniform float uPrismEvenBlue[3];\n"
"uniform float uPrismOddBlue[3];\n"
"uniform float uPrismCenterGreen;\n"
    "uniform float uPanelOpacity;\n"
    "uniform vec3 uToneCtrl;\n"
    "uniform float uToneBoost;\n"
    "uniform vec4 uRefractTint;\n"
    "uniform vec4 uSurfaceTint;\n"
    "uniform float uSurfaceMode;\n"
    "uniform float uEdgeMode;\n"
    "uniform vec4 uEdgeTint;\n"
    "uniform float uEdgeTintAlpha;\n"
    "uniform float uEdgeAngle;\n"
    "uniform float uEdgeFalloff;\n"
    "uniform float uEdgeAlpha;\n"
    "uniform float uEdgeWidth;\n"
    "uniform float uEdgeBlur;\n"
    "uniform vec4 uInsetTint;\n"
    "uniform vec2 uInsetShift;\n"
    "uniform float uInsetReach;\n"
    "uniform float uInsetAlpha;\n"
    "uniform float uGlowOn;\n"
    "uniform vec2 uGlowAt;\n"
    "uniform float uGlowReach;\n"
    "uniform float uGlowLevel;\n"
    "uniform float uSceneOn;\n"
    "uniform float uSolidScene;\n"
    "uniform vec2 uStretchScale;\n"
    "uniform float uStretchMix;\n"
    "uniform vec4 uAbsentTint;\n"
    "uniform float uTrackOn;\n"
    "uniform vec4 uTrackRect;\n"
    "uniform float uTrackRound;\n"
    "uniform vec4 uTrackTint;\n"
    "uniform float uShadeMode;\n"
    "uniform vec4 uShadeTint;\n"
    "uniform vec2 uShadeShift;\n"
    "uniform float uShadeReach;\n"
    "uniform vec2 uShadeBody;\n"
    "\n"
    "float pickCorner(vec2 c, vec4 r) {\n"
    "    vec2 col = mix(vec2(r.x, r.w), vec2(r.y, r.z), step(0.0, c.x));\n"
    "    return mix(col.x, col.y, step(0.0, c.y));\n"
    "}\n"
    "float boxMetric(vec2 p, vec2 semi, float r) {\n"
    "    vec2 reach = abs(p) - semi + vec2(r);\n"
    "    float pocket = min(max(reach.x, reach.y), 0.0);\n"
    "    vec2 over = max(reach, vec2(0.0));\n"
    "    float arc = sqrt(dot(over, over)) - r;\n"
    "    return pocket + arc;\n"
    "}\n"
    "vec2 boxNormal(vec2 p, vec2 semi, float r) {\n"
    "    vec2 q = abs(p) - semi + vec2(r);\n"
    "    vec2 over = max(q, vec2(0.0));\n"
    "    float len2 = dot(over, over);\n"
    "    vec2 arc = len2 > 1.0e-8 ? over * inversesqrt(len2) : vec2(0.0);\n"
    "    float horiz = step(q.y, q.x);\n"
    "    vec2 axisPick = vec2(horiz, 1.0 - horiz);\n"
    "    float outside = step(0.0, max(q.x, q.y));\n"
    "    vec2 dir = axisPick + (arc - axisPick) * outside;\n"
    "    return dir * sign(p);\n"
    "}\n"
    "float fuseFields(float a, float b, float k) {\n"
    "    float gap = max(k - abs(a - b), 0.0);\n"
    "    return min(a, b) - gap * gap * 0.25 / k;\n"
    "}\n"
    "float fuseWeight(float a, float b, float k) {\n"
    "    return clamp((k + b - a) * 0.5 / k, 0.0, 1.0);\n"
    "}\n"
    "float lensCurve(float x) {\n"
    "    float t = clamp(x, 0.0, 1.0);\n"
    "    return t * tan(asin(t) * 0.5);\n"
    "}\n"
    "vec2 unitOrZero(vec2 v) {\n"
    "    float len = length(v);\n"
    "    return len > 0.0001 ? v / len : vec2(0.0);\n"
    "}\n"
    "vec2 sceneUv(vec2 pixel) {\n"
    "    vec2 storage = max(uSampleTexel, vec2(1.0));\n"
    "    vec2 limit = max((uSampleSpan - vec2(0.5)) / storage, vec2(0.0));\n"
    "    vec2 uv = vec2(pixel.x / storage.x, (uSampleSpan.y - pixel.y) / storage.y);\n"
    "    return clamp(uv, vec2(0.0), limit);\n"
    "}\n"
    "vec4 gatherRead(vec2 pixel) {\n"
    "    if (uGatheredOn > 0.5) {\n"
    "        vec2 uv = vec2(pixel.x * uGatherPitch.x,\n"
    "                       uGatherRows - pixel.y * uGatherPitch.y) / uGatherTexel;\n"
    "        return texture(uGathered, clamp(uv, vec2(0.0), uGatherLimit));\n"
    "    }\n"
    "    return texture(uScene, sceneUv(pixel));\n"
    "}\n"
    "vec4 sceneSample(vec2 pixel) {\n"
    "    vec4 c = gatherRead(pixel);\n"
    "    float base = clamp(c.a, 0.0, 1.0);\n"
    "    c.rgb = clamp(c.rgb, vec3(0.0), vec3(base));\n"
    "    c.rgb = max(c.rgb, vec3(uDarkGuard * base));\n"
    "    c.rgb += uAbsentTint.rgb * uAbsentTint.a * (1.0 - base);\n"
    "    c.a = base + uAbsentTint.a * (1.0 - base);\n"
    "    return c;\n"
    "}\n"
    "float trackMask(vec2 p) {\n"
    "    vec2 halfSpan = (uTrackRect.zw - uTrackRect.xy) * 0.5;\n"
    "    vec2 center = (uTrackRect.xy + uTrackRect.zw) * 0.5;\n"
    "    float r = min(uTrackRound, min(halfSpan.x, halfSpan.y));\n"
    "    float f = boxMetric(p - center, halfSpan, r);\n"
    "    float feather = max(fwidth(f), 1.0);\n"
    "    return 1.0 - smoothstep(-0.5 * feather, 0.5 * feather, f);\n"
    "}\n"
    "vec4 sceneLayer(vec2 coord) {\n"
    "    vec2 pixel = coord + uSampleShift;\n"
    "    vec4 base = sceneSample(pixel);\n"
    "    float amount = clamp(uStretchMix, 0.0, 1.0);\n"
    "    if (amount <= 0.0) return base;\n"
    "    vec2 scale = uStretchScale;\n"
    "    if (scale.x <= 0.001 || scale.y <= 0.001) return base;\n"
    "    vec2 center = uSampleSpan * 0.5;\n"
    "    vec2 moved = center + (pixel - center) / scale;\n"
    "    if (uTrackOn < 0.5) {\n"
    "        return mix(base, sceneSample(moved), amount);\n"
    "    }\n"
    "    float cover = trackMask(moved - uSampleShift) * uTrackTint.a * amount;\n"
    "    vec4 layer = vec4(uTrackTint.rgb * cover, cover);\n"
    "    return layer + base * (1.0 - layer.a);\n"
    "}\n"
    "vec4 sceneBlurred(vec2 coord) {\n"
    "    if (uSceneOn < 0.5) {\n"
    "        vec4 absent = uAbsentTint;\n"
    "        if (uSolidScene > 0.5) absent.a = 1.0;\n"
    "        return absent;\n"
    "    }\n"
    "    vec4 c = sceneLayer(coord);\n"
    "    if (c.a <= 0.001) return vec4(0.0);\n"
    "    c.rgb = clamp(c.rgb / c.a, 0.0, 1.0);\n"
    "    if (uSolidScene > 0.5 && c.a > 0.001) c.a = 1.0;\n"
    "    return c;\n"
    "}\n"
    "vec3 toneMap(vec3 c, vec3 ctrl) {\n"
    "    float brightness = ctrl.x;\n"
    "    float contrast = ctrl.y;\n"
    "    float saturation = ctrl.z;\n"
    "    vec3 base = vec3(0.213, 0.715, 0.072) * (1.0 - saturation);\n"
    "    float lift = 0.5 - contrast * 0.5 + brightness;\n"
    "    return vec3(dot(c, contrast * (base + vec3(saturation, 0.0, 0.0))) + lift,\n"
    "                dot(c, contrast * (base + vec3(0.0, saturation, 0.0))) + lift,\n"
    "                dot(c, contrast * (base + vec3(0.0, 0.0, saturation))) + lift);\n"
    "}\n"
    "void main() {\n"
    "    vec2 halfSpan = uPanelSpan * 0.5;\n"
    "    vec2 centered = vLocal - halfSpan;\n"
    "    float round = pickCorner(centered, uCornerRadii);\n"
    "    vec2 bodyCoord = centered;\n"
    "    vec2 bodyHalf = halfSpan;\n"
    "    if (uDropRect.z >= 0.0 && uDropRect.w >= 0.0) {\n"
    "        bodyHalf = uDropRect.zw;\n"
    "        bodyCoord = centered - (uDropRect.xy - halfSpan);\n"
    "        round = uDropRound;\n"
    "    }\n"
    "    float field = boxMetric(bodyCoord, bodyHalf, round);\n"
    "    if (uShadeMode > 0.5) {\n"
    "        vec2 shadeHalf = max(uShadeBody, vec2(1.0)) * 0.5;\n"
    "        float shadeRound = min(round, min(shadeHalf.x, shadeHalf.y));\n"
    "        float reach = max(uShadeReach, 1.0) * 0.57735;\n"
    "        float own = boxMetric(centered, shadeHalf, shadeRound);\n"
    "        float band = clamp(own / reach, -3.0, 3.0);\n"
    "        float halo = exp(-0.5 * band * band);\n"
    "        float moved = boxMetric(centered + uShadeShift, shadeHalf, shadeRound);\n"
    "        halo *= smoothstep(-0.75, 0.75, moved);\n"
    "        fragOut = vec4(uShadeTint.rgb, uShadeTint.a * halo);\n"
    "        return;\n"
    "    }\n"
    "    bool strandLive = (uStrandMerge > 0.0001) && (uStrandRect.z >= 0.0)\n"
    "                   && (uStrandRect.w >= 0.0);\n"
    "    float strandWeight = 1.0;\n"
    "    vec2 strandCoord = vec2(0.0);\n"
    "    if (strandLive) {\n"
    "        strandCoord = centered - (uStrandRect.xy - halfSpan);\n"
    "        float strandField = boxMetric(strandCoord, uStrandRect.zw, uStrandRound);\n"
    "        strandWeight = fuseWeight(field, strandField, uStrandMerge);\n"
    "        field = fuseFields(field, strandField, uStrandMerge);\n"
    "    }\n"
    "    float neckWeight = 1.0;\n"
    "    vec2 neckCoord = vec2(0.0);\n"
    "    if (uFeedMerge > 0.0001) {\n"
    "        neckCoord = centered - (uFeedRect.xy - halfSpan);\n"
    "        float neckField = boxMetric(neckCoord, uFeedRect.zw, uFeedRound);\n"
    "        neckWeight = fuseWeight(field, neckField, uFeedMerge);\n"
    "        field = fuseFields(field, neckField, uFeedMerge);\n"
    "    }\n"
    "    float lensOn = (uLensHeight > 0.0001 && uLensAmount > 0.0) ? 1.0 : 0.0;\n"
    "    float insideDepth = min(field, 0.0);\n"
    "    float lensT = lensOn * clamp(1.0 - (-insideDepth / max(uLensHeight, 0.001)),\n"
    "                                 0.0, 1.0);\n"
    "    float lensShift = lensCurve(lensT) * (-uLensAmount) * lensOn;\n"
    "    float bodyRound = min(round, min(bodyHalf.x, bodyHalf.y));\n"
    "    vec2 lensDir = unitOrZero(boxNormal(bodyCoord, bodyHalf, bodyRound));\n"
    "    if (strandLive) {\n"
    "        float strandRound = min(uStrandRound, min(uStrandRect.z, uStrandRect.w));\n"
    "        vec2 strandDir = unitOrZero(boxNormal(strandCoord, uStrandRect.zw, strandRound));\n"
    "        lensDir = unitOrZero(lensDir * strandWeight + strandDir * (1.0 - strandWeight));\n"
    "    }\n"
    "    if (uFeedMerge > 0.0001) {\n"
    "        float neckRound = min(uFeedRound, min(uFeedRect.z, uFeedRect.w));\n"
    "        vec2 neckDir = unitOrZero(boxNormal(neckCoord, uFeedRect.zw, neckRound));\n"
    "        lensDir = unitOrZero(lensDir * neckWeight + neckDir * (1.0 - neckWeight));\n"
    "    }\n"
    "    lensDir = unitOrZero(lensDir + uLensDepth * unitOrZero(centered));\n"
    "    vec2 sampleCoord = vLocal + lensShift * lensDir;\n"
    "    float spread = uSpectral;\n"
    "    if (lensOn < 0.5) spread = 0.0;\n"
    "    vec4 color;\n"
    "    if (spread > 0.0) {\n"
    "        float denom = max(bodyHalf.x * bodyHalf.y, 1.0);\n"
    "        float strength = uSpectral\n"
    "            * clamp((centered.x * centered.y) / denom, -1.0, 1.0);\n"
    "        vec2 stride = lensShift * lensDir * strength;\n"
    "        const float pairAlpha = 1.0 / 7.0;\n"
    "        vec4 mid = sceneBlurred(sampleCoord);\n"
    "        vec4 sum = vec4(0.0, mid.g * uPrismCenterGreen, 0.0,\n"
    "                        mid.a * pairAlpha);\n"
    "        for (int k = 0; k < 3; ++k) {\n"
    "            vec4 ahead = sceneBlurred(sampleCoord + stride * uPrismDist[k]);\n"
    "            vec4 behind = sceneBlurred(sampleCoord - stride * uPrismDist[k]);\n"
    "            vec4 pair = ahead + behind;\n"
    "            vec4 skew = ahead - behind;\n"
    "            sum.r += pair.r * uPrismEvenRed[k] + skew.r * uPrismOddRed[k];\n"
    "            sum.g += pair.g * uPrismEvenGreen[k] + skew.g * uPrismOddGreen[k];\n"
    "            sum.b += pair.b * uPrismEvenBlue[k] + skew.b * uPrismOddBlue[k];\n"
    "            sum.a += pair.a * pairAlpha;\n"
    "        }\n"
    "        color = sum;\n"
    "    } else {\n"
    "        color = sceneBlurred(sampleCoord);\n"
    "    }\n"
    "    vec3 ctrl = uToneCtrl;\n"
    "    if (uToneBoost > 0.5) ctrl.z *= 1.5;\n"
    "    color.rgb = toneMap(color.rgb, ctrl);\n"
    "    color.a *= uPanelOpacity;\n"
    "    color.rgb += uRefractTint.rgb * uRefractTint.a * color.a;\n"
    "    if (uSurfaceMode > 1.5) {\n"
    "        float surfaceAlpha = clamp(uSurfaceTint.a, 0.0, 1.0);\n"
    "        float outAlpha = color.a + surfaceAlpha * (1.0 - color.a);\n"
    "        if (outAlpha > 0.001) {\n"
    "            color.rgb = (uSurfaceTint.rgb * surfaceAlpha\n"
    "                      + color.rgb * color.a * (1.0 - surfaceAlpha)) / outAlpha;\n"
    "        } else {\n"
    "            color.rgb = vec3(0.0);\n"
    "        }\n"
    "        color.a = outAlpha;\n"
    "    } else if (uSurfaceMode > 0.5) {\n"
    "        float luma = dot(color.rgb, vec3(0.213, 0.715, 0.072));\n"
    "        vec3 hue = uSurfaceTint.rgb * (0.35 + 1.3 * luma);\n"
    "        color.rgb = mix(color.rgb, hue, 0.75 * uSurfaceTint.a);\n"
    "        color.a = max(color.a, 0.75 * uSurfaceTint.a);\n"
    "    }\n"
    "    if (uEdgeMode > 0.5) {\n"
    "        float insideMask = 1.0 - smoothstep(0.0, 1.15, field);\n"
    "        float edgeRound = min(round, min(bodyHalf.x, bodyHalf.y));\n"
    "        vec2 edgeGrad = boxNormal(bodyCoord, bodyHalf, edgeRound);\n"
    "        float bandWidth = max(uEdgeWidth, 0.5);\n"
    "        float bandBlur = max(uEdgeBlur, 0.5);\n"
    "        float depth = max(-field, 0.0);\n"
    "        float band = 1.0 - smoothstep(bandWidth, bandWidth + bandBlur * 2.0, depth);\n"
    "        vec2 edgeAxis = vec2(cos(uEdgeAngle), sin(uEdgeAngle));\n"
    "        float align = dot(edgeGrad, edgeAxis);\n"
    "        float magnitude = max(align, -align);\n"
    "        float sharp = pow(magnitude, max(uEdgeFalloff, 0.001));\n"
    "        if (uEdgeMode > 3.5) {\n"
    "            float lambert = dot(lensDir, vec2(cos(uEdgeAngle), sin(uEdgeAngle)));\n"
    "            float rimDir = pow(clamp(lambert * 0.5 + 0.5, 0.0, 1.0),\n"
    "                               max(uEdgeFalloff, 0.001));\n"
    "            float gain = mix(0.34, 1.0, rimDir);\n"
    "            float add = band * uEdgeAlpha * uEdgeTintAlpha * insideMask * gain;\n"
    "            color.rgb += uEdgeTint.rgb * add;\n"
    "            color.a = clamp(color.a + add, 0.0, 1.0);\n"
    "        } else if (uEdgeMode > 2.5) {\n"
    "            float add = uEdgeAlpha * uEdgeTintAlpha * band * insideMask;\n"
    "            color.rgb += uEdgeTint.rgb * add;\n"
    "            color.a = clamp(color.a + add, 0.0, 1.0);\n"
    "        } else if (uEdgeMode > 1.5) {\n"
    "            float add = sharp * band * uEdgeAlpha * uEdgeTintAlpha\n"
    "                      * smoothstep(-0.15, 0.35, align) * insideMask;\n"
    "            color.rgb = mix(color.rgb, vec3(1.0), add);\n"
    "            color.a += add * (1.0 - color.a);\n"
    "        } else {\n"
    "            float gate = step(0.0, align);\n"
    "            float add = sharp * band * uEdgeAlpha * uEdgeTintAlpha * insideMask * gate;\n"
    "            color.rgb += uEdgeTint.rgb * add;\n"
    "            color.a = clamp(color.a + add, 0.0, 1.0);\n"
    "        }\n"
    "    }\n"
    "    if (uInsetAlpha > 0.001) {\n"
    "        vec2 insetCoord = centered - uInsetShift;\n"
    "        float insetField = boxMetric(insetCoord, halfSpan, round);\n"
    "        float insetReach = max(uInsetReach, 0.75);\n"
    "        float insetDepth = max(-insetField, 0.0);\n"
    "        float insetT = insetDepth / insetReach;\n"
    "        float soft = exp(-2.0 * insetT * insetT);\n"
    "        float shifted = smoothstep(-0.5, 0.5, insetField);\n"
    "        float inside = 1.0 - smoothstep(0.0, max(fwidth(field), 0.75), field);\n"
    "        float amount = max(soft * 0.52, shifted) * inside * uInsetAlpha;\n"
    "        color.rgb = mix(color.rgb, uInsetTint.rgb, clamp(amount, 0.0, 1.0));\n"
    "        color.a += amount * (1.0 - color.a);\n"
    "    }\n"
    "    if (uGlowOn > 0.5 && uGlowLevel > 0.001) {\n"
    "        float level = uGlowLevel;\n"
    "        float spot = smoothstep(uGlowReach, uGlowReach * 0.5,\n"
    "                                distance(vLocal, uGlowAt));\n"
    "        float add = 0.08 * level + 0.15 * level * spot;\n"
    "        color.rgb += vec3(add);\n"
    "        color.a = clamp(color.a + add, 0.0, 1.0);\n"
    "    }\n"
    "    float cover = max(fwidth(field), 1.15);\n"
    "    color.a *= 1.0 - smoothstep(0.0, cover, field);\n"
    "    fragOut = color;\n"
    "}\n";

}

const char* quadVertexSource() { return kQuadVertexSource; }
const char* gatherFragmentSource() { return kGatherFragmentSource; }
const char* panelFragmentSource() { return kPanelFragmentSource; }

}
}
